trigger:
  branches:
    include:
      - main

jobs:
  - job: run_42crunch_audit
    displayName: 'Run Audit'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        displayName: Install Python
        inputs:
          versionSpec: '3.11'
          addToPath: true
          architecture:  x64
      - task: APISecurityAuditFreemium@1
        displayName: Audit API Specifications
        inputs:
          enforceSQG: false
          logLevel: DEBUG
          sarifReport: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'
          exportAsPDF: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.pdf'    
      - task: PublishBuildArtifacts@1
        displayName: publishAuditSarif
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'
          ArtifactName: 'CodeAnalysisLogs'
          publishLocation: 'Container'  
      - task: PublishBuildArtifacts@1
        displayName: publishAuditPDF
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.pdf'
          ArtifactName: 'Reports'
          publishLocation: 'Container'