trigger:
  branches:
    include:
      - azuredevops-integration

jobs:
  - job: run_42crunch_audit
    displayName: 'Run Audit'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.11'
          addToPath: true
          architecture:  x64
      - task: APISecurityAuditFreemium@1
        inputs:
          enforceSQG: false
          logLevel: DEBUG
          sarifReport: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'
          exportAsPDF: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.pdf'    