openapi: 3.0.1
info:
  title: OpenWeather Map
  version: "1.0"
servers:
  - url: https://api.openweathermap.org/data/2.5
security:
  - apikey: []
paths:
  /weather:
    get:
      tags:
        - weather
      description: You can call by city name or city name and country code. API
        responds with a list of results that match a searching word.
      operationId: GetWeatherByCityName
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: ""
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
            Access-Control-Allow-Credentials:
              schema:
                type: boolean
            Access-Control-Allow-Methods:
              schema:
                type: string
          content:
            application/json:
              schema:
                type: object
                properties:
                  base:
                    type: string
                  clouds:
                    type: object
                    properties:
                      all:
                        type: integer
                  cod:
                    type: integer
                  coord:
                    type: object
                    properties:
                      lat:
                        type: number
                      lon:
                        type: number
                  dt:
                    type: integer
                  id:
                    type: integer
                  main:
                    type: object
                    properties:
                      humidity:
                        type: integer
                      pressure:
                        type: integer
                      temp:
                        type: number
                      temp_max:
                        type: number
                      temp_min:
                        type: number
                  name:
                    type: string
                  sys:
                    type: object
                    properties:
                      country:
                        type: string
                      id:
                        type: integer
                      message:
                        type: number
                      sunrise:
                        type: integer
                      sunset:
                        type: integer
                      type:
                        type: integer
                  visibility:
                    type: integer
                  weather:
                    type: array
                    items:
                      type: object
                      properties:
                        description:
                          maxLength: 50
                          minLength: 5
                          pattern: ^[a-zA-Z]+$
                          type: string
                        icon:
                          type: string
                        id:
                          type: integer
                        main:
                          type: string
                  wind:
                    type: object
                    properties:
                      deg:
                        type: integer
                      speed:
                        type: number
              example:
                base: stations
                clouds:
                  all: 0
                cod: 200
                coord:
                  lat: 51.51
                  lon: -0.13
                dt: 1494501600
                id: 2643743
                main:
                  humidity: 42
                  pressure: 996
                  temp: 290.98
                  temp_max: 293.15
                  temp_min: 288.15
                name: London
                sys:
                  country: GB
                  id: 5091
                  message: 0.0055
                  sunrise: 1494476035
                  sunset: 1494531651
                  type: 1
                visibility: 10000
                weather:
                  - description: haze
                    icon: 50d
                    id: 721
                    main: Haze
                wind:
                  deg: 100
                  speed: 7.7
components:
  securitySchemes:
    apikey:
      type: apiKey
      name: APPID
      in: query
